name: Run Maven Test
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha }}
  APPLITOOLS_SERVER_URL : 'eyesapi.applitools.com'
  APPLITOOLS_DISABLED: 'false'
jobs:
  Run-TestNG-PageObjectAPI-Suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup OpenJDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'maven'
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1.0.8
      - name: Exported
        run: export
      - name: Chrome Version
        run: ${CHROME_BIN} --version
      - name: Chromdriver Version
        run: which chromedriver && chromedriver --version
      - name: Maven Test
        run: mvn -P pageobject clean test --file pom.xml
